CREATE TABLE dbo.Source1 ( 
    Id INT NOT NULL, 
    Value NVARCHAR(160) NULL, 
    CONSTRAINT PK_Source1 PRIMARY KEY (Id)
)
CREATE TABLE dbo.Source2 ( 
    Id INT NOT NULL, 
    Value NVARCHAR(160) NULL, 
    CONSTRAINT PK_Source2 PRIMARY KEY (Id)
)


CREATE TABLE dbo.Target1 ( 
    Id INT IDENTITY NOT NULL, 
    Value NVARCHAR(160) NULL, 
    CONSTRAINT PK_Target1 PRIMARY KEY (Id)
)
CREATE TABLE dbo.Target2 ( 
    Id INT IDENTITY NOT NULL, 
    Value NVARCHAR(160) NULL, 
    CONSTRAINT PK_Target2 PRIMARY KEY (Id)
)

INSERT INTO Source1 (Id, Value) VALUES (1, '1-1');
INSERT INTO Source1 (Id, Value) VALUES (2, '1-2');

INSERT INTO Source2 (Id, Value) VALUES (1, '2-1');
INSERT INTO Source2 (Id, Value) VALUES (2, '2-2');
