select 
	table_schema, 
	table_name, 
	column_name,
	is_nullable,
	data_type,
	character_maximum_length,
	numeric_precision,
	numeric_scale,
	column_default
from information_schema.columns
where 
		table_schema <> 'information_schema' 
		and table_schema <> 'pg_catalog' 
		and table_schema !~ '^pg_toast' 
		and 'table:' || table_schema || '.' || table_name =[OBJECT_ID_CONDITION]
order by ordinal_position
