CREATE TABLE Test1 (
	ID_TEST1 INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(20) NOT NULL
);

CREATE TABLE Test2 (
	ID_TEST2 INT PRIMARY KEY IDENTITY,
  ID_TEST1 INT NOT NULL REFERENCES Test1(ID_TEST1), 
	Name NVARCHAR(20) NOT NULL
);

